#!/bin/bash
set -eu

if ! charm whoami > /dev/null; then
    echo "Not logged into charm store" 2>&1
    exit 1
fi
URL=$(charm push "$CHARM_BUILD_DIR/$CHARM.charm" "cs:~$NAMESPACE/$CHARM" | yq r - url)
echo "Uploaded: $URL"

IMAGE_NAME="$CHARM-image"
IMAGE="$CHARM"
IMAGE_REV=$(charm attach cs:~"$NAMESPACE"/"$CHARM" --channel unpublished "$IMAGE_NAME=$IMAGE" | tail -n1 | sed -e 's/uploaded revision \([0-9]*\) of.*/\1/')
echo "Attached: $IMAGE_NAME-$IMAGE_REV"

if [ "$CHANNEL" != unpublished ]; then
    charm release "$URL" --channel "$CHANNEL" --resource "$IMAGE_NAME"-"$IMAGE_REV"
    echo "Released to: $CHANNEL"
fi
