#!/usr/bin/env bash
set -eu

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
(
 cp Dockerfile install-sriov-cni.sh "$tmpdir"
 cd "$tmpdir"
 git clone https://github.com/intel/sriov-cni --branch v2.3 --depth 1
 cd sriov-cni
 make
 cd ..
 DOCKER_BUILDKIT=1 docker build . -t sriov-cni
)
